"""add group_booking_code to bookings

Revision ID: 1263fe8f5988
Revises: 8b2fea6589c8
Create Date: 2026-05-15 15:34:39.538777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1263fe8f5988'
down_revision = '8b2fea6589c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_booking_code', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_group_booking_code'), ['group_booking_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_group_booking_code'))
        batch_op.drop_column('group_booking_code')

    # ### end Alembic commands ###
