"""initial schema with all fields

Revision ID: 13a79cb6165c
Revises: 
Create Date: 2026-05-11 18:00:38.747068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a79cb6165c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('layout_name', sa.String(length=50), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active_account', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('voyages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=80), nullable=False),
    sa.Column('destination', sa.String(length=80), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('arrival_at', sa.DateTime(), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voyages_departure_at'), ['departure_at'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voyage_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.String(length=8), nullable=False),
    sa.Column('passenger_name', sa.String(length=120), nullable=False),
    sa.Column('passenger_phone', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('boarding_point', sa.String(length=80), nullable=True),
    sa.Column('dropping_point', sa.String(length=80), nullable=True),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('booking_code', sa.String(length=30), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voyage_id', 'seat_id', name='uq_voyage_seat')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_code'), ['booking_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_booking_code'))

    op.drop_table('bookings')
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voyages_departure_at'))

    op.drop_table('voyages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('buses')
    # ### end Alembic commands ###
